### ISSUE TITLE
Opening Gui issues.

### ISSUE THREAD

**Issue by psxlover** [bfox1/HardCoreTrees#1]
> OtherWise, by using the positions you normally would in getClientGuiElement()
> i get a Null TileEntity. Since its trying to open TileEntity on the Player.

That's simply because those are the positions you open it with... https://github.com/bfox1/HardCoreTrees/blob/master/src/main/java/net/bfox1/hardcoretrees/common/blocks/SawMill.java#L144

**Comment by bfox1** [comment]
..... I feel like a dummy:/ this is what happens when i try to code late at night
